development:
    dialect: postgres
    datasource: user=postgres password=postgres dbname=myapp sslmode=disable
    dir: migrations/
    table: migrations

production:
    dialect: postgres
    datasource: ${DATABASE_URL}
    dir: migrations/
    table: migrations
