version: '3'
services:
  postgres:
    image: "postgres"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_db:
    driver: local
